# Generated by Django 2.2.4 on 2020-07-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_author_book_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_who_wrote_this',
        ),
    ]
