# Generated by Django 3.0.8 on 2020-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_quote_quote_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='book_app.User'),
        ),
    ]
