# Generated by Django 3.0.8 on 2020-07-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_quote_user_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user_likes',
            new_name='users_likes',
        ),
    ]
