# Generated by Django 3.0.8 on 2020-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_auto_20200730_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_info',
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
