# Generated by Django 3.0.8 on 2020-07-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.CharField(default='old dojo', max_length=255),
            preserve_default=False,
        ),
    ]
