# Generated by Django 3.0.8 on 2020-07-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas', '0002_dojo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='description',
        ),
    ]
